# Generated by Django 4.2.30 on 2026-04-19 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
