# Generated by Django 6.0.3 on 2026-03-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('actor', 'Oyuncu'), ('musician', 'Müzisyen'), ('dancer', 'Dansçı'), ('model', 'Model'), ('other', 'Diğer')], max_length=20)),
                ('title', models.CharField(help_text='Örn: Profesyonel Tiyatro Oyuncusu', max_length=255)),
                ('experience', models.TextField(help_text='Daha önce yer aldığınız projeler')),
                ('skills', models.CharField(help_text='Örn: Eskrim, Ehliyet, Akıcı İngilizce', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
