# Generated by Django 4.2.30 on 2026-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_talentlisting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.RemoveField(
            model_name="job",
            name="producer",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="talentlisting",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="video",
            name="user",
        ),
        migrations.RemoveField(
            model_name="videoreaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="videoreaction",
            name="video",
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="TalentListing",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.DeleteModel(
            name="VideoReaction",
        ),
    ]
